# Generated by Django 2.2.4 on 2019-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiriyaniCatModel',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BiriyaniModel',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=50)),
                ('b_price', models.FloatField()),
                ('b_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_many_one.BiriyaniCatModel')),
            ],
        ),
    ]
